### ISSUE TITLE
Hotfixes borked

### ISSUE THREAD

**Issue by Juicyexe** [Tk-Glitch/PKGBUILDS#579] opened 2020-09-04 22:43 UTC
when compiling with makepkg -si i get:
`=> WARNING: HALP! We got some hotfixes for your current tree!
Do you want to apply them all with no further prompt?
> Y/n : 
  -> Hotfixing...
error: could not revert 5b4b877488... ntdll: Move the reserved area functions to avoid forward declarations.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
==> ERROR: Patch application has failed. The error was logged to /home/juicyexe/PKGBUILDS/wine-tkg-git/wine-tkg-git/prepare.log for your convenience.
==> ERROR: A failure occurred in prepare().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done`
[prepare.log](https://github.com/Tk-Glitch/PKGBUILDS/files/5177217/prepare.log)
i have attached the log.

**Comment by Tk-Glitch** [comment] 2020-09-05 11:06
Duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/130

Fixed with https://github.com/Frogging-Family/wine-tkg-git/commit/a4e7388240c909f77e5b7d005f1fd33e29674bf0

**Closed by Tk-Glitch** 2020-09-05 11:06 UTC
