### ISSUE TITLE
Game: The King of Fighters 98 and 2002 - No music

### ISSUE THREAD

**Issue by SteveDoido** [Tk-Glitch/PKGBUILDS#562] opened 2020-05-18 05:53 UTC
I have a problem where using any version of wine (or proton), except for the official ones, stops the music from being loaded. This version is no different.
I don't know if it is a pronlem exclusive to the GOG release (which is the one I own), but it is really perplexing.
The games use XACT (.xwb) for both the music and SFX, yet the sound effects are loaded but the music isn't. Enabling FSYNC and Feral Gamemode seem to crash the games when it loads up music too.
I wonder if there is some band-aid solution to make it work.

**Comment by Tk-Glitch** [comment] 2020-05-18 14:28
`except for the official ones` is the most perplexing part. A log would likely tell more.

**Comment by SteveDoido** [comment] 2020-05-19 04:19
> `except for the official ones` is the most perplexing part. A log would likely tell more.
I recorded the terminal output of the application. I closed it as soon as I could after music was supposed to play. Also, when I closed the game, instead of simply closing, it crashed (kind of the same thing, but still).
[kof98log.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/4648173/kof98log.txt)

**Comment by Tk-Glitch** [comment] 2020-05-19 10:35
After some testing and some digging, those games seem to be actually retarded.

To begin with, the "official ones" did't fix it for me, at all. I have found that the issue happens on Windows too for a large amount of players (and I could indeed reproduce the issue in a Windows VM), from XP to 10. Apparently some got it fixed by installing the game on C: - that didn't work for me - then I later found out that apparently the game *requires* to be installed on a drive with 512 bytes/sector. I didn't try that.

I have attempted a variety of other things with zero success. At this point I'm not sure Wine is the main culprit. I have a couple more things to try but I invite you to open an issue on winehq nonetheless.

All my tests were done on the Steam versions of both games.

**Comment by Tk-Glitch** [comment] 2020-06-09 10:50
So I was able to give this another look, and it seems I can get BGM back on a mainline build. Staging seems to be a no-go, so this is likely an issue with staging's winepulse patches. I wasn't able to find any obvious issue logged though. I'll do a couple more tests.

If my assumption is correct, `_staging_pulse_disable="true"` should bring BGM back on staging.

**Comment by Tk-Glitch** [comment] 2020-06-09 11:37
Sadly I was wrong. It seems to be something else, but at least it's now absolutely clear it's a staging issue as clean mainline works, while clean staging doesn't. I also tested with a very customized mainline-based build and it works fine there as well.

Setting `_use_staging="false"` in your .cfg will get you BGM back.

**Comment by Tk-Glitch** [comment] 2020-06-09 12:45
Success! The next likely culprit was actually it. Staging's `xactengine-initial` patchset is responsible for BGMs going silent. I'll add a toggle and continue on my quest of getting a useful log to report upstream.

**Closed** 2020-06-09 12:56 UTC
