### ISSUE TITLE
Valve's Proton fullscreen patches

### ISSUE THREAD

**Issue by kicsyromy** [Tk-Glitch/PKGBUILDS#44] opened 2018-11-11 09:39 UTC
Would there be any interest in adding Valve's proton patches for changing a game's internal resolution without changing the desktop resolution?
I have extracted the necessary bits from Valve's WINE fork and created a patch that should apply cleanly on top of staging (at least it does for me).
If you would be interested in adding it to your repository maybe we can work together on it.

Thanks for the great work,
Romeo
[00_valve_proton_fullscreen_hack.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2569213/00_valve_proton_fullscreen_hack.zip)

**Comment by Tk-Glitch** [comment] 2018-11-12 21:15
Sure thing! I'll check your patch asap and see how it goes.

**Comment by Tk-Glitch** [comment] 2018-11-12 21:34
Looks good to me. The patch won't apply cleanly on plain wine but indeed does with staging. @kicsyromy If you want to make a PR, please add staging as a condition for the patch. Else I can add it myself and give you credit for it of course.

**Comment by kicsyromy** [comment] 2018-11-13 13:43
@Tk-Glitch Thanks for the feedback, I'll make a PR this afternoon. Separately I'll try and have a look if we can get it to apply cleanly to plain WINE.

**Comment by kicsyromy** [comment] 2018-11-13 13:47
@neVERberleRfellerER The border scrolling issue sounds pretty bad but I'm a bit more concerned about the Gallium Nine issue. I mean the reason I wanted this patch in the first place was so that I can scale up to 4k (from something lower) and some DX9 games don't maintain 60FPS at 4K on my configuration.
I can't promise anything but I can take a look at the patch set and see if there is anything that can be done.

**Comment by neVERberleRfellerER** [comment] 2018-11-13 15:31
@kicsyromy Adding support for new API is non-trivial. I was looking how your patchet works with Vulkan witohut having any Vulkan specific code and the answer unfortunately is, that it does not work, probably because it's missing this:
https://github.com/ValveSoftware/wine/commit/81f198f28e51f68619ed3ed29f0d59e9c39dce59#diff-4c6867ea59c7b81579004f69edb55aaa
Something similar would have to be implementd on top of nine patches.

Now that I think about it, it would be indeed good to have nine scaling too, because my beloved STALKER does indeed not run at 60 FPS at 4k with nine and last time I tried DX11 mode with DXVK as faster alternative, it was causing random pretty-miuch-untracable GPU lock ups.

**Comment by kicsyromy** [comment] 2018-11-13 18:34
@neVERberleRfellerER I've updated the patch with vulkan support and made a quick build. I haven't updated the PR with it yet since I haven't had a chance to test it.
[valve_proton_fullscreen_hack-staging-with-vulkan.zip](https://github.com/Tk-Glitch/PKGBUILDS/files/2577543/valve_proton_fullscreen_hack-staging-with-vulkan.zip)

**Comment by neVERberleRfellerER** [comment] 2018-11-14 17:22
@kicsyromy It seems to work fine after 20 minutes of testing. I am pleasantly surprised by quality: S.T.A.L.K.E.R. Anomaly with DXVK at 1920x1080 mapped to 3840x2160 looks great. It is actually so great that I couldn't see any difference in quality most of the time except in font rendering.

**Comment by Tk-Glitch** [comment] 2018-11-15 12:39
@kicsyromy My limited testing also looked good.

**Comment by kicsyromy** [comment] 2018-11-15 17:58
I haven't had a chance to create a new PR, but hopefully by the weekend I'll get around to it.

Thanks for the feedback 🙂

**Comment by Kron4ek** [comment] 2018-11-17 11:41
Thank you for the patch. I tested it in some games (Grim Dawn, STALKER, Sacred) and it worked good. But i found out that it doesn't work in Heroes of Might and Magic 5, i just see black square in left corner after launch. But this game works with Proton, so i suppose the problem is in the patch itself. Can someone else test it with HoMM 5?
![2018-11-17 16-22-06](https://user-images.githubusercontent.com/13851877/48660626-9ae4c000-ea86-11e8-9457-37bef4a5f36b.png)

**Comment by Tk-Glitch** [comment] 2018-11-17 13:44
@Kron4ek So the game works fine with the exact same wine build but without that patch?

**Comment by kicsyromy** [comment] 2018-11-17 14:31
@Kron4ek I don't have HoMM5 so I can't test it unfortunately.
But perhaps @Tk-Glitch is right and it might be some other patch that Proton carries.
I'll have a look at the logs when I get home maybe there might be some insight there.

**Comment by Kron4ek** [comment] 2018-11-17 15:55
@Tk-Glitch 
@kicsyromy 
I tested the game with the exact the same build without "fullscreen_hack" patch and the game doesn't work too, it even not renders black square. So it's actually not the patch problem, but the Wine problem.

However, it works with virtual desktop enabled. Apparently Proton has some patches which makes the game work without virtual desktop or it's just a regression in Wine newer than 3.16, i don't know.

**Comment by Tk-Glitch** [comment] 2018-11-17 16:03
@Kron4ek 3.20 seems to be coming with a good amount of issues. It would be interesting to check the game with 3.19 (`d279bc2` for plain and `5a85ab0` for staging) and see how it goes. But yeah that definitely looks like a regression and not an issue with the FS hack patch itself.

**Comment by Kron4ek** [comment] 2018-11-17 17:17
I tested the game with 3.11, 3.16, 3.18 and 3.19, even with 3.5 - no success, works only with virtual desktop enabled. So HoMM5 works without virtual desktop only under Proton, interesting.

**Comment by Tk-Glitch** [comment] 2018-11-17 17:46
There might be another patch in proton helping then.. Or the runtime maybe?

**Comment by Kron4ek** [comment] 2018-11-17 19:00
@Tk-Glitch Yes, i think another patch or many patches. Definetly not thr Runtime, because i use Proton outside of Steam.

@neVERberleRfellerER It runs with nothing visible, i see just my desktop, and with "fullscreen_hack" it renders at least black square (screenshot in my comment above). I hear intro videos, so i suppose it not freezes. if someone interested, [that's](https://youtu.be/xNl-YlV4DK8) how it launches under Proton, and [that's](https://youtu.be/vlWOguYvYe8) under vanilla Wine (or staging, doesn't matter).

Actually that's not a big problem, because the game still runs with virtual desktop. Just interesting what patch is exactly makes the game work under Proton. Thanks for the link, i will test this patch later.

**Comment by Tk-Glitch** [comment] 2018-11-24 15:46
Public testing didn't reveal any specific issue with the patch, so I'm closing this :)

**Closed by Tk-Glitch** 2018-11-24 15:46 UTC
Labels: enhancement
