### ISSUE TITLE
[wine-tkg-git] A failure ocurred in ()build

### ISSUE THREAD

**Issue by rossophantasma** [Tk-Glitch/PKGBUILDS#429] opened 2019-12-19 14:04 UTC
make[1]: Leaving directory '/home/blackfuture/Downloads/PKGBUILDS-master/wine-tkg-git/src/wine-tkg-staging-fsync-git-64-build/dlls/actxprxy'
==> ERROR: A failure occurred in build().
    Aborting...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done
  -> Compilation time for 64-bit wine: 

real    0m49.595s
user    3m51.246s
sys     1m8.525s

Running fresh latest arch linux with latest fsync kerne (5.4.3), gcc, make and mingw are all installed (gcc and mingw using the tkglitch make files). System is Ryzen 5 1400, 12 GB of DDR4 3000 RAM, Arch is on a m.2 120gb SSD.

**Comment by Tk-Glitch** [comment] 2019-12-19 14:31
It builds fine here (just checked).
Could you please provide your .cfg and if possible the full log of your compilation? Thanks!

**Comment by rossophantasma** [comment] 2019-12-19 14:46
Sure, would you mind telling me where to found the log? I settled for the .tar.xz release, but trying to build anything (specifically the linux 5.4-tkg) gives me the same error. The customization.cfg from linux-5.4-tkg (cfg format is not supported it seems)
[customization.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3984096/customization.txt)

**Comment by Tk-Glitch** [comment] 2019-12-19 15:33
Now that you say it's happening with both kernel and wine, I'm pretty sure I know what the problem is..
Since you have a 1st gen Zen CPU, you're likely affected by a regression of GCC 9.2 that will lead to segfaults 90% of the time, at the very least while building wine and the linux kernel. Using GCC 9.1 instead should fix your issues if you want to build your own packages.
@varris1 is affected by that issue and might have more input.

**Comment by rossophantasma** [comment] 2019-12-19 16:12
> Now that you say it's happening with both kernel and wine, I'm pretty sure I know what the problem is..
> Since you have a 1st gen Zen CPU, you're likely affected by a regression of GCC 9.2 that will lead to segfaults 90% of the time, at the very least while building wine and the linux kernel. Using GCC 9.1 instead should fix your issues if you want to build your own packages.
> @varris1 is affected by that issue and might have more input.

Thanks! I do have a 1st gen Ryzen, i'll try what you say ASAP.

**Comment by rossophantasma** [comment] 2019-12-19 16:50
> Now that you say it's happening with both kernel and wine, I'm pretty sure I know what the problem is..
> Since you have a 1st gen Zen CPU, you're likely affected by a regression of GCC 9.2 that will lead to segfaults 90% of the time, at the very least while building wine and the linux kernel. Using GCC 9.1 instead should fix your issues if you want to build your own packages.
> @varris1 is affected by that issue and might have more input.

Hey Tk, do i need mingw-w64-gcc? Or can i build the standard GCC to make it work? I am having trouble finding the AUR 9.1.0 MinGW.

**Comment by Tk-Glitch** [comment] 2019-12-19 17:22
You *could* use mostlyportable (https://github.com/Tk-Glitch/PKGBUILDS/tree/master/mostlyportable-gcc) but ultimately you don't require mingw to build wine. It might become really needed in the future for anticheats to work, but right now it's not a problem.

**Comment by Tk-Glitch** [comment] 2020-02-22 21:52
The GCC 9.2.1 update has fixed the 9.1.0 regression on Zen so I think I can close this. However mingw was broken in the meantime, kinda: https://github.com/Tk-Glitch/PKGBUILDS/issues/501

**Closed by Tk-Glitch** 2020-02-22 21:52 UTC
Labels: stuff
