### ISSUE TITLE
Huge PBA regression in 3.20?

### ISSUE THREAD

**Issue by stanczew** [Tk-Glitch/PKGBUILDS#49] opened 2018-11-12 22:48 UTC
Hi,

I don't really know where to put this issue, i.e. what is the "official unofficial" PBA contact point, but your repo has a lot of traction, so I guess it's the best bet to ask people.

After updating from 3.19 to 3.20 (Wine + Staging + esync + PBA), I have noticed a pretty significant regression in DX9 games. It is so big that disabling PBA actually increases the performance.

To confirm this, I have built wine-staging from Arch Linux repository with just PBA patches added from your repo (so, wine-staging 3.19 with PBA319+.patch, and wine-staging 3.20 with PBA320+.patch). No other patches were applied. I then created a clean wineprefix with just corefonts installed.

Results:
Watching a replay in Starcraft II with PBA disabled, I get about 50-55 FPS at the beginning and just over 40 FPS at a certain time mark. This is true for both 3.19 and 3.20; on 3.20 I get a bit more FPS (3-5), but nothing too significant.
With PBA enabled on 3.19, the FPS jumps from 50 to 90 and from 40 to 75 – so it's almost a 2× improvement. However with PBA enabled on 3.20, there is a drop instead, from 55 to 35 and from 43 to 29.

I also checked in 32-bit Diablo III (which also uses DX9) by just launching the game directly to the login screen. With PBA disabled on both versions I get 220 FPS; with PBA enabled on 3.19 it increases to 265, but on 3.20 it instead decreases to 170.

Games using DXVK are not affected (I tested it in my default prefix, not the clean one above); for example 64-bit Diablo improved by about 10 FPS, and enabling/disabling PBA has no effect on it.

I tested everything on Arch with GTX 1060 6 GB (driver version 410.66) and double-checked the D3 scenario with AMD RX 560 2 GB (Mesa 18.2.4).

Can anyone else confirm/deny this?

**Comment by neVERberleRfellerER** [comment] 2018-11-12 22:57
Yeah, PBA is broken. In Gothic 2 it decreases FPS from stable 60 (manually limited) to 8. Sacred is similar. I though, it's caused by something else and I didn't have time time inspect it in more detail. But now that you have same problem, it's probably just broken.
It floods stderr with
`0032:fixme:d3d_perf:wined3d_buffer_gl_map Fences not used for persistent buffer maps on CS thread, using glFinish (flags: 40001000)`

**Comment by Tk-Glitch** [comment] 2018-11-12 23:00
I'm not playing anything anymore using wined3d but considering the changes in 3.20 I'm not really surprised something is broken. Considering PBA has been maltreated during the whole 3.19->3.20 merge window, I've been considering dropping the patchset until it gets mainlined (supposedly Valve is aiming for that). If someone finds a fix, I'm all ears.

**Comment by folknor** [comment] 2018-11-14 00:11
Just adding my two cents here for posterity after tkg informed me he had a ticked for it
```
[12:21 AM] folk: @T₭₲ I just wanted to note that in previous wine versions, pba literally doubles the FPS for me in SC2 - I've not tried yet with 3.20. I don't expect anything, and I'm not asking for anything
[12:22 AM] folk: just figured it might be worth knowing
...
[12:39 AM] T₭₲: @folk The patchset would need a rework, though it might be small. Currently, after rebasing, it's spamming a fence error that may be all there is to fix. I'll give it another look but I'm not sure I'm the right guy for the task.
[12:40 AM] folk: indeed, I suspect (and hope) firerat or bobwya, or someone who knows what's up, will take a look at some point
[12:41 AM] folk: I was just throwing my 2 cents in and hoping that if that day comes, you'll re-introduce it in your patchset
[12:46 AM] T₭₲: Well, it's still in my repo in its currently broken form for now. I have an issue open about it, and hopefully someone will be able to figure it out indeed. Firerat might be able to.
[12:50 AM] folk: indeed, I just compared esync-staging-pba-3.16 with tkg-3.20, and the FPS goes from 89-130 to ~50
[12:51 AM] folk: as far as I know, esync-staging-pba-3.16 is the last known version where all components actually functioned
[12:51 AM] folk: if I'm wrong about that, please do tell :P
[12:54 AM] T₭₲: 3.18 should have been fine
[12:56 AM] T₭₲: 3.19 was fixed after the original 3.19-tkg release on lutris. No idea if Strider built it afterwards as some kind of hotfix.
```

I'm quite sure 3.18 crashes on certain SC2 Arcade maps for me, but I frankly don't remember. 3.16 works fine, except sometimes the sound crackles. `esync-staging-pba-nopulse-3.16` seems best the best runner as of today.

**Comment by bobwya** [comment] 2018-11-21 08:13
@Tk-Glitch 

FYI. I've refactored **wine-pba** my repository: [Github: bobwya/gentoo-wine-pba](https://github.com/bobwya/gentoo-wine-pba) using 1 patch / 1 wine source file. This is the readability tidy up I previously discussed with you.

A problem I have with testing Fallout 4, is that the stock Wine renderer is in a pretty busted state for this game (vs. DXVK). So what's a Wine bug, vs. issues introduced by **wine-pba**??!!
However, further testing off Fallout 4, with Wine Staging 3.17 and Wine Staging 3.18, leads me to the conclusion that a small additional patch is required. Otherwise the game will consistently hit a graphics pipeline state where the world is drawn with no textures, etc. This is my _hack_: [gentoo-wine-pba/wine-staging-pba/f11563c65fa50e2f8b7e39cade34bb7a998b26f7/wine-pba-dlls-wined3d-query_c.patch](https://github.com/bobwya/gentoo-wine-pba/blob/master/wine-staging-pba/f11563c65fa50e2f8b7e39cade34bb7a998b26f7/wine-pba-dlls-wined3d-query_c.patch). To emphasis it is just a hack. I've done quite a bit of game play with Fallout 4, and it appears to be stable (for me) now, with Wine Staging 3.17 and 3.18, plus **PBA_ENABLE=1**.

As an aside I've done some tidy up work on @Firerat 's setup code. This tries ("very hard"!) now to set the **geo** and **cb** heap sizes to sane defaults (when no **env** overrides are specified). I've added in some rudimentary detection, to see if the **cb** heap is required (for newer Wine versions). See: [ gentoo-wine-pba/wine-staging-pba/f11563c65fa50e2f8b7e39cade34bb7a998b26f7/wine-pba-dlls-wined3d-device_c.patch](https://github.com/bobwya/gentoo-wine-pba/blob/master/wine-staging-pba/f11563c65fa50e2f8b7e39cade34bb7a998b26f7/wine-pba-dlls-wined3d-device_c.patch).

You'd probably want to pull these patch updates in for your **PKGBUILD**. Certainly I wouldn't recommend enabling PBA with Wine Staging 3.17 / 3.18, without the **query.c** patch.

I've blacklisted support for Wine versions >=3.19 in my repository and **app-emulation/wine-staging** and **app-emulation/wine-vanilla** ebuilds. The work required to fix PBA support is much more extensive, at this stage.

I suspect that this area is priority for the Wine D3D developers. They've recently added in hooks for ARB storage. They frequently express appreciation of the **wine-pba** implementation (to be fair it is quite elegant). Plus it's pretty obvious that Wine's current D3D11 performance is completely atrocious!

**Comment by mirh** [comment] 2018-11-24 22:45
You might be interested to
https://bugs.winehq.org/show_bug.cgi?id=46068 and
https://gitlab.com/Firer4t/wine-pba/issues/5

**Comment by ronoverdrive** [comment] 2019-04-23 16:51
Honestly I think at this point we should just close this thread as PBA development is apparently abandoned. From what I understand Firerat only worked on PBA to improve performance in WoW when DXVK was experimental and before Blizzard added DX12 support. All signs are pointing to D9VK for future support for D3D9 anyway so I suggest making PBA a legacy patch and call it a day.

**Comment by neVERberleRfellerER** [comment] 2019-04-23 17:45
@ronoverdrive This thread should probably be closed since PBA is dead, but FYI: D9VK is irrelevant here, because PBA was also important for old Direct3D 7/DDraw games and there is no alternative. For exmaple, Sacred on RX 580 and Ryzen 7 1700 works only at 10 FPS in some cities a and even slower in areas with a lot of effects (Tyr Harad is extreme example because it's totally unplayable without PBA) but it was around 40 FPS with PBA (even in Tyr Harad). Modded Gothic 2 currently runs at around 20 FPS in city and slower in some unnamed locations in Jharkendar, but it was smooth 60 FPS with PBA.

**Comment by ronoverdrive** [comment] 2019-04-23 18:04
@neVERberleRfellerER honestly you can use dgVoodoo2 for d3d7/draw and d3d8.x games in combination with DXVK if needed. Even then I didn't say ditch PBA entirely, just relegate it to LEGACY status for older WINE versions which is no change to what is currently being done. Also FYI, Josh has also shown interest in adding support for d3d8 and I think d3d7/draw into D9VK later down the line.

**Comment by Tk-Glitch** [comment] 2019-04-23 18:11
PBA is being reworked and enhanced for an upcoming mainline integration btw. But yeah, acomminos's implementation can probably be considered dead right now.

**Closed** 2019-04-23 18:12 UTC
Labels: help wanted
