### ISSUE TITLE
Final Fantasy XIV Launcher Patch

### ISSUE THREAD

**Issue by fosspill** [Tk-Glitch/PKGBUILDS#361] opened 2019-10-29 16:08 UTC
Hi!
Due to the recent FFXIV launcher patch which, again, broke wine compatibility I've been experimenting and discovered that setting ```_ffxivlauncher_fix="true"``` does not add any new lines  "last_build_config.log".

I assume the patch didn't get applied?

**Comment by Tk-Glitch** [comment] 2019-10-30 00:08
That patch is deprecated and not meant to be applied to a wine version newer than https://github.com/wine-mirror/wine/commit/d535df42f665a097ec721b10fb49d7b18f899be9 (4.10), which fixed the issue that this workaround addressed. As such, it simply gets ignored as long as your targeted tree contains that commit.

The problem with ffxiv right now is the new launcher. The old launcher works "fine" as of the commit above (or that legacy patch/workaround before it) but the new launcher doesn't, and that patch sadly won't help as the problem is different.

The only workaround I'm aware of right now is to set `Browser` value to `1` in `FFXIV_BOOT.CFG`.

**Comment by fosspill** [comment] 2019-10-30 07:17
That makes sense - but the interesting thing is that others have pointed out that "ge-protonified-4.10" seem to make the new launcher functional, albeit a bit incorrectly rendered. I believe this specific build comes with the FFXIV launcher workaround.

Would it be easy for me to apply this patch regardless to see if it actually makes a difference or if it's something else with ge-protonofied-4.10 that makes it work?

**Comment by Tk-Glitch** [comment] 2019-10-30 10:33
Absolutely!
You only have to grab the patch from the game-specific/legacy dir (`wine-tkg-git/wine-tkg-patches/game-specific/legacy/ffxiv-launcher-workaround.patch`), put it in the `wine-tkg-git/wine-tkg-userpatches` dir and change its extension to ".mypatch". You'll see a prompt about it during your next compilation.

**Comment by Tk-Glitch** [comment] 2019-10-30 12:31
Thinking about it, that hack might actually force the launcher to fallback to that Browser 1 setting.

**Comment by fosspill** [comment] 2019-10-30 12:39
Maybe, that's what I'd like to find out, so thank you for pointing out the obvious choice of applying it as a userpatch!

Based on responses on reddit and discord though I think "Browser 2" switches to CEF when "istransgaming" is present.

Currently compiling wine to answer for sure :)

**Comment by fosspill** [comment] 2019-10-30 13:19
After building current wine with your pkgbuild and the ffxiv-launcher-workaround.patch I can confirm that the new launcher (Browser 2) functions. It doesn't render perfectly, but it works!

This leads me to believe that:
- They are working on making it render properly with CEF when istransgaming is detected.
- We might want to consider the ffxiv-launcher-workaround.patch as a valid patch again, for now. No longer legacy?
- Whatever is causing issues with wine's ieframe should be resolved.  (Created a bug here: https://bugs.winehq.org/show_bug.cgi?id=48006)

**Comment by Tk-Glitch** [comment] 2019-10-30 13:21
I got curious and made a test on my end. Using the patch indeed helps and the launcher kinda works, with issues.
I'll remove the check and allow one to enable the patch back.

**Comment by Tk-Glitch** [comment] 2019-11-06 12:55
The issue with the patch being legacy and ignored on recent wine version has been fixed. Closing.

**Closed by Tk-Glitch** 2019-11-06 12:55 UTC

**Comment by fosspill** [comment] 2020-02-18 18:04
A quick update on this. It seems like they (square enix) finally broke the new launcher's patching in wine. 

The launcher renders partially - but the login/patching window no longer renders.

The launcher patch no longer fixes it completely and it seems the only "fix" is to edit config file to switch to Browser 1.

**Comment by Tk-Glitch** [comment] 2020-02-18 18:06
I was made aware indeed. That's pretty sad and annoying.
