### ISSUE TITLE
Lutris' "Disable desktop effects - on" cause weird behavior with wine-tkg.

### ISSUE THREAD

**Issue by dron1885** [Tk-Glitch/PKGBUILDS#130] opened 2019-03-07 16:55 UTC
I currently have only Warframe installed, so tested only with this game and Lutris.

Prior to version tkg-3.19 (esynch-3.18) game have worked fine, only bug was spontaneous sound crackling.
Starting with tkg-3.19 (all tkg versions up to tkg-4.2) following behavior was encountered:
1) If game was previously started in fullscreen mode it will crash on an attempt to enter main menu (other than that seems to work OK, but hard to test due to limited ability to avoid main menu). 
2) If game was previously started in windowed mode it would not appear, but game will be running in background (as sound appear to work normally and game's process use standard amount of RAM and %CPU).
3) For Borderless Fullscreen game runs normally.
4) When game started in Borderless or normal Fullscreen mode when switching (alt-tabbing) to different window or changing workspace there is no mouse pointer. 

As a proton fullscreen compositor bypass was only related change between version 3.18 and 3.19 so this patch is my suspect.

Latest tkg-versions are fixing my sound problem, but their wonky behavior causes a mild discomfort.

Is there any way to disable the patch for fuhrer testings?
System: Arch Linux, Mesa drivers (RX 580), issue occurs with both Cinnamon and XFCE desktops.

**Comment by Tk-Glitch** [comment] 2019-03-07 17:06
Well, yes. If you haven't created a specific custom config file in `~/.config/frogminer/` and aren't using a preset, the file used to customize your build is `customization.cfg` (https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/customization.cfg).

The `_FS_bypass_compositor` and `_proton_fs_hack` are the lines you want to edit in that case. You can enable `_FS_bypass_compositor` on its own, but it's a dependency of `_proton_fs_hack` so you'll want to disable it as well if it applies.

These two are disabled by default though so you might be using some preset or custom config I guess ?

**Comment by dron1885** [comment] 2019-03-07 18:00
As far as I know I didn't use any custom configs. 

After some more testing I found out that sometime in the past I set "Disable desktop effects" as on by default in Lutris (and silly me completely forgot about it). Switching it off removes all problem (at least for tkg-4.2). 

It is technically solves my issue, but I can reliably reproduce previously described behavior. "Disable desktop effects - on" works fine with esynch-3.18 and standard wine-staging-4.2, Only tkg builds are affected. I'll install some other games and test with them to see if this affects only one title.

**Comment by Tk-Glitch** [comment] 2019-03-07 18:20
Maybe the compositor bypass patch conflicts with the lutris option.. I'll check what the option does exactly but it might be that simple. Thanks for letting me know about that.

**Comment by ronoverdrive** [comment] 2019-03-10 18:07
@dron1885 have you build wine-tkg from source using TkG's PKGBUILD script or are you just using the pre-built binaries available in Lutris?

**Comment by dron1885** [comment] 2019-03-11 12:25
@ronoverdrive Currently I use builds provided within Lutris.

**Comment by ronoverdrive** [comment] 2019-03-12 03:10
@dron1885 well if you're not using the "tkg-protonified" builds the Proton patches are not applied so its not likely a conflict with the patches. I suggest giving the tkg-protonified build or using the PKGBUILD with the Proton options enabled in the customization.cfg file and try with "Disable Desktop Effects" turned off. Optionally if you decide to build it yourself using the PKGBUILD you could also try enabling FAudio in the customization.cfg for the sound issues (be sure to install both faudio-git and lib32-faudio-git AUR packages).

**Comment by Tk-Glitch** [comment] 2019-04-25 09:45
I can't do more than already done. It's not a bug on my side. So closing for now. If it's still an issue, better forward it to Lutris issue tracker.

**Closed by Tk-Glitch** 2019-04-25 09:45 UTC
Labels: bug
