### ISSUE TITLE
have compile problem with wine 

### ISSUE THREAD

**Issue by d4vid1** [Tk-Glitch/PKGBUILDS#163] opened 2019-04-15 18:55 UTC
../../../dlls/user32/libuser32.cross.a ../../../dlls/advapi32/libadvapi32.cross.a -pipe -O2 -ftree-vectorize -ftree-slp-vectorize
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
collect2: error: ld returned 1 exit status
winegcc: x86_64-w64-mingw32-gcc failed
make[1]: *** [Makefile:476: advapi32_test.exe] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lgcc_eh
collect2: error: ld returned 1 exit status
winegcc: x86_64-w64-mingw32-gcc failed
make[1]: *** [Makefile:482: advapi32_test-stripped.exe] Fehler 2
make[1]: Verzeichnis „/home/*/PKGBUILDS/wine-tkg-git/src/wine-tkg-staging-esync-marchopt-git-64-build/dlls/advapi32/tests“ wird verlassen
make: *** [Makefile:9230: dlls/advapi32/tests] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
  -> Removed BIG_UGLY_FROGMINER - Ribbit
  -> Removed Proton-tkg token - Valve Ribbit
  -> exit cleanup done

**Comment by Tk-Glitch** [comment] 2019-04-16 01:51
I can't reproduce.
The whole make output would help. Also, are you able to compile stuff with your mingw compiler? How did you install it?

**Comment by Tk-Glitch** [comment] 2019-04-25 09:42
So, it's been 10 days, no answer, closing.

**Closed by Tk-Glitch** 2019-04-25 09:42 UTC
Labels: question
