### ISSUE TITLE
linux53-tkg: Unable to boot with Navi GPU

### ISSUE THREAD

**Issue by xk0niR** [Tk-Glitch/PKGBUILDS#359] opened 2019-10-24 07:55 UTC
Hello,
I can´t seem to boot this kernel. After systemd printing its version number I just get a black screen (so I don´t see lightdm). PC seems frozen and I have to reboot. Could this be related to my 5700 XT? It should be supported since 5.3 and I can boot the default kernel and (self compiled) XanMod without any problems.

Some system info:
 - Arch Linux (with systemd)
 - Grub for boot
 - CPU: 3700X
 - GPU: 5700 XT

linux54-rc-tkg is booting for me (but since its RC and doesn´t include as many patches as 53 I don´t really want to use it yet).

Thanks a lot!

**Comment by fluffykittyrevenge** [comment] 2019-10-24 13:49
Care to post your last_build_config.log and/or the customization.cfg used?

**Comment by fluffykittyrevenge** [comment] 2019-10-24 17:13
It's usually in PKGBUILDS/linux53-tkg

Well, there might be another issue going on -- setting it to `2. Ryzen Desktop` won't allow for changes in the default customization.cfg to take effect, just what's in the `PKGBUILDS/linux53-tkg/linux53-tkg-config/ryzen-desktop-profile.cfg`.  Since you mentioned SGDT which isn't in that config, I'm wondering if you edited `PKGBUILDS/linux53-tkg/customization.cfg` after setting `_OPTIPROFILE="2"`.

So first either set `_OPTIPROFILE="1"` to use the settings in `PKGBUILDS/linux53-tkg/customization.cfg` or copy  customization.cfg to `~/.config/frogminer/linux53-tkg.cfg` and use that to configure everything.

With your CPU, you should have SGDT, etc instructions enabled.

If you're getting to systemd, the kernel is booting.  If you're not getting to the desktop from there, it could be a few different issues like Mesa, the Kernel, the firmware, libdrm, etc.  Since 5.4rc works, stock 5.3 works, but not 5.3-tkg, it makes me doubt most other things outside of possible config issues.

Here's my config updated to use zen2 with user patches disabled.  I'm lazy and copy/pasted the ones I use over to linux53-tkg instead of writing it all out in the config :disappointed: 

And I'm using customization.cfg and I clearly know the correct way to do it :disappointed: :nauseated_face: 

```
# linux53-TkG config file


#### MISC OPTIONS #### 

# External config file to use - If the given file exists in path, it will override default config (customization.cfg) - Default is ~/.config/frogminer/linux52-tkg.cfg
_EXT_CONFIG_PATH=~/.config/frogminer/linux53-tkg.cfg

# Set to anything else than "true" to limit cleanup operations and keep source and files generated during compilation.
# Default is "true".
_NUKR="true"

# Custom compiler root dirs - Leave empty to use system compilers
# Example: CUSTOM_GCC_PATH="/home/frog/PKGBUILDS/mostlyportable-gcc/gcc-mostlyportable-9.2.0"
CUSTOM_GCC_PATH=""

# Set to the number corresponding to a predefined profile to use it. Current list of available profiles :
# 1 - Custom (meaning nothing will be enforced and you get to configure everything)
# 2 - Ryzen desktop (performance)
# 3 - Generic Desktop (Performance)
_OPTIPROFILE="1"

# Set to true to bypass makepkg.conf and use all available threads for compilation. False will respect your makepkg.conf options.
_force_all_threads="false"

# Set to true to use modprobed db to clean config from unneeded modules. Speeds up compilation considerably. Requires root - https://wiki.archlinux.org/index.php/Modprobed-db
# !!!! Make sure to have a well populated db !!!! - Leave empty to be asked about it at build time
_modprobeddb="false"

# Set to "1" to call make menuconfig or "2" to call make nconfig before building the kernel. Set to false to disable and skip the prompt.
_menunconfig="false"

# Set to true to generate a kernel config fragment from your changes in menuconfig/nconfig. Set to false to disable and skip the prompt.
_diffconfig="false"

# Set to the file name where the generated config fragment should be written to. Only used if _diffconfig is active.
_diffconfig_name=""

#### KERNEL OPTIONS ####

# Name of the default config file to use from the linux???-tkg-config folder. Arch default is "config.x86_64".
_configfile="config.x86_64"

# Disable some non-module debugging - See PKGBUILD for the list
_debugdisable="true"

# LEAVE AN EMPTY VALUE TO BE PROMPTED ABOUT FOLLOWING OPTIONS AT BUILD TIME

# CPU scheduler - Options are "pds", "bmq", "cfs" or "cfsturbo" - "pds" is the recommended option for gaming
_cpusched="pds"

# CPU sched_yield_type - Choose what sort of yield sched_yield will perform
# For PDS and MuQSS: 0: No yield. (Recommended option for gaming on PDS and MuQSS)
#                    1: Yield only to better priority/deadline tasks. (Default - can be unstable with PDS on some platforms)
#                    2: Expire timeslice and recalculate deadline. (Usually the slowest option for PDS and MuQSS, not recommended)
# For BMQ:           0: No yield.
#                    1: Deboost and requeue task. (Default)
#                    2: Set rq skip task.
_sched_yield_type="0"

# Round Robin interval is the longest duration two tasks with the same nice level will be delayed for. When CPU time is requested by a task, it receives a time slice equal
# to the rr_interval in addition to a virtual deadline. When using yield_type 2, a low value can help offset the disadvantages of rescheduling a process that has yielded.
# MuQSS default: 6ms"
# PDS default: 4ms"
# BMQ default: 4ms"
# Set to "1" for 2ms, "2" for 4ms, "3" for 6ms, "4" for 8ms, or "default" to keep the chosen scheduler defaults.
_rr_interval="default"

# Set to "true" to disable FUNCTION_TRACER/GRAPH_TRACER, lowering overhead but limiting debugging and analyzing of kernel functions - Kernel default is "false"
_ftracedisable="true"

# Set to "true" to disable NUMA, lowering overhead, but breaking CUDA/NvEnc on Nvidia equipped systems - Kernel default is "false"
_numadisable="false"

# Set to "1" to use CattaRappa mode (enabling full tickless), "2" for tickless idle only, or "0" for periodic ticks.
# Full tickless can give higher performances in various cases but, depending on hardware, lower consistency. Just tickless idle can perform better on some platforms (mostly AMD based).
_tickless="1"

# Setting this to to "true" can improve latency on PDS (at the cost of throughput) and improve throughput on other schedulers (at the cost of latency) - Can improve VMs performance - Kernel default is "false"
_voluntary_preempt="true"

# Set to "true" to enable Device Tree and Open Firmware support. If you don't know about it, you don't need it - Default is "false"
_OFenable="false"

# Set to "true" to use ACS override patch - https://wiki.archlinux.org/index.php/PCI_passthrough_via_OVMF#Bypassing_the_IOMMU_groups_.28ACS_override_patch.29 - Kernel default is "false"
_acs_override="true"

# Set to "true" to add back missing symbol for AES-NI/AVX support on ZFS - https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/linux/kernel/export_kernel_fpu_functions.patch - Kernel default is "false"
_zfsfix="true"

# Set to "true" to enable support for fsync, an experimental replacement for esync found in Valve Proton 4.11+ - https://steamcommunity.com/games/221410/announcements/detail/2957094910196249305
_fsync="true"

# A selection of patches from Zen/Liquorix kernel and additional tweaks for a better gaming experience (ZENIFY) - Default is "true"
_zenify="true"

# Set to true to enable emulation of the SGDT, SIDT, and SMSW instructions for 64-bit processes. May help with crashing in certain 64-bit Windows games under Wine, on UMIP-enabled systems.
_umip_instruction_emulation="true"

# compiler optimization level - 1. Optimize for performance (-O2); 2. Optimize harder (-O3); 3. Optimize for size (-Os) - Kernel default is "2"
_compileroptlevel="2"

# CPU compiler optimizations - Defaults to generic optimizations if left empty
# AMD CPUs : "k8" "k8sse3" "k10" "barcelona" "bobcat" "jaguar" "bulldozer" "piledriver" "steamroller" "excavator" "zen" "zen2"
# Intel CPUs : "mpsc"(P4 & older Netburst based Xeon) "atom" "core2" "nehalem" "westmere" "silvermont" "sandybridge" "ivybridge" "haswell" "broadwell" "skylake" "skylakex" "cannonlake" "icelake"
# Other options :
# - "generic" (to share the package between machines with different CPUs)
# - "native" (use compiler autodetection and will prompt for P6_NOPS - Selecting your arch manually in the list above is recommended instead of this option)
_processor_opt="zen2"

# SMT (Hyperthreading) aware nice priority and policy support (SMT_NICE) - Kernel default is "true" - You can disable this on non-SMT/HT CPUs for lower overhead
_smt_nice="true"

# Trust the CPU manufacturer to initialize Linux's CRNG (RANDOM_TRUST_CPU) - Kernel default is "false"
_random_trust_cpu="false"

# Timer frequency - "500", "750" or "1000" - More options available in kernel config prompt when left empty depending on selected cpusched - Kernel default is "500"
_timer_freq="750"

# Default CPU governor - "performance", "ondemand" (tweaked), "schedutil" or leave empty for default (schedutil on AMD and legacy Intel, intel_pstate on modern Intel) - Enforcing an option will disable intel_pstate altogether!
_default_cpu_gov="schedutil"

# On some platforms, an acpi_cpufreq bug affects performance negatively. Set to "true" to disable it as a workaround, but it will use more power.
# https://github.com/Tk-Glitch/PKGBUILDS/issues/263
_disable_acpi_cpufreq="false"


#### SPESHUL OPTION ####

# If you want to bypass the stock naming scheme and enforce something else (example : "linux") - Useful for some bootloaders requiring manual entry editing on each release.
# !!! It will also change pkgname - If you don't explicitely need this, don't use it !!!
_custom_pkgbase=""


#### USER PATCHES ####

# community patches - add patches (separated by a space) of your choice by name from the community-patches dir
# example: _community_patches="clear_nack_in_tend_isr.myrevert ffb_regression_fix.mypatch 0008-drm-amd-powerplay-force-the-trim-of-the-mclk-dpm-levels-if-OD-is-enabled.mypatch"
_community_patches=""

# You can use your own patches by putting them in the same folder as the PKGBUILD and giving them the .mypatch extension.
# You can also revert patches by putting them in the same folder as the PKGBUILD and giving them the .myrevert extension.

# Also, userpatches variable below must be set to true for the above to work.
_user_patches="false"

# Apply all user patches without confirmation - !!! NOT RECOMMENDED !!!
_user_patches_no_confirm="true"


#### CONFIG FRAGMENTS ####

# You can use your own kernel config fragments by putting them in the same folder as the PKGBUILD and giving them the .myfrag extension.

# Also, the config fragments variable below must be set to true for the above to work.
_config_fragments="true"

# Apply all config fragments without confirmation - !!! NOT RECOMMENDED !!!
_config_fragments_no_confirm="false"

```

I'm using these patches if you're interested.  You probably don't want the zstd one (you have to updated mkinitcpio.conf to use zstd if you do or you really won't have a kernel that boots)
```
0008-drm-amd-powerplay-force-the-trim-of-the-mclk-dpm-levels-if-OD-is-enabled.mypatch  amd-mckl-switching.mypatch
amdgpu_bulk_moves.mypatch                                                              ffb_regression_fix.mypatch
amdgpu_extratemps-5.3.mypatch                                                          zstd.mypatch

```

**Comment by Tk-Glitch** [comment] 2019-10-25 11:15
Can you boot to TTY? Also, you're not using modprobed-db, right?

**Comment by xk0niR** [comment] 2019-10-25 13:02
I´ve got modprobed-db installed but I am not using it right now (_modprobeddb="false" in config).
I can boot to TTY by adding "nomodeset" to the kernel bootline. On TTY7 (where X normally starts) there is just a blinking underscore _. Switching to other TTY works (so my keyboard isn´t frozen like before).

**Comment by Tk-Glitch** [comment] 2019-10-25 13:12
So you should be able to get a dmesg for us to have a look at :frog: 
That being said, did you try with a different CPU scheduler (BMQ/CFS/MuQSS)? Your issue is pretty unique so far, even among Zen2+Navi users.

**Comment by fluffykittyrevenge** [comment] 2019-10-25 13:31
I read a thing on the Arch forums where F2FS will do a complete fsck if the kernel version changes...that's not what's going on here is it?  I can see that appearing to cause a system freeze. 

[There's actually a reported bug in the Arch Bug Tracker](https://bugs.archlinux.org/task/63743?string=f2fs&project=1&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=) that sounds very similar to what you're experiencing because the F2FS fsck doesn't support the read-only to read/write handoff to systemd.

Edit /etc/fstab and set the pass to 0 for /.  If you're suffering from the same issue on the Arch Bug Tracker, that should "fix" it.

You also might want to consider adding f2fs to your MODULES=() line. 

I consider it safe practice to include the modules to the file systems the system uses there.

**Comment by xk0niR** [comment] 2019-10-25 14:51
I don´t even see the message "failed to open the device". My fs_passno was already 0 for /.
I even removed now fsck from my HOOKS inside mkinitcpio.conf and did a mkinitcpio -p for generating. Still the same result. It also should fail for other kernels then I guess. And your right, I should add f2fs to MODULES, I will in the future.

My fstab:
# /dev/nvme0n1p3
UUID=554c3917-9333-4761-b11e-adbd217107bc	/         	f2fs      	rw,relatime,lazytime,background_gc=on,discard,no_heap,inline_xattr,inline_data,inline_dentry,flush_merge,extent_cache,mode=adaptive,active_logs=6,alloc_mode=default,fsync_mode=posix	0 0

# /dev/nvme0n1p1
UUID=4E50-E66A      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro	0 2

# /dev/nvme0n1p2
UUID=ef49ac6d-2af5-43d9-8f91-b447103ef312	none      	swap      	defaults  	0 0

tmpfs /tmp tmpfs rw,nodev,nosuid,exec,mode=777,noatime 0 0

Here is dmesg after booting with nomodeset. Uh, this seems so weird... 
[boot.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3772579/boot.log)

**Comment by fluffykittyrevenge** [comment] 2019-10-25 16:01
Looks like you're having an issue with ECC memory.  Do you have it enabled in your UEFI?

Anyhoo, a quick look at the kernel commit history shows a recent pull regarding EDAC that may be what is making it work with 5.4.  I pulled that merge request against 5.3.7 and came up with this patch.  You might give it a shot and see if it helps.

[5.4_edac.mypatch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3772820/5.4_edac.mypatch.txt)

It patches cleanly, but I'm still compiling it.  If you have a faster system and see this first...just sayin.

**Comment by xk0niR** [comment] 2019-10-25 17:09
I am not sure about my UEFI settings they got reset the last time I upgraded the motherboard firmware (so it should be default now). I´ll check it, thanks (by ECC you mean "Error-correcting code"?).

I´ve compiled the kernel with your patch (using CFS scheduler) and it still crashes for me.

**Comment by fluffykittyrevenge** [comment] 2019-10-25 17:43
Yeah, error correcting code.  FWIW, that patch does work on my system and I have ECC memory. 

Since you said the settings reset upon the last firmware update, check your ram settings there.  That's a likely candidate based on the error message.

Based on your log above, `ecc_enable_override=1` added to the kernel command line could possibly override the error you're getting if the above doesn't work, but that's a bit of a dirty solution nor would it work if it's a firmware issue which is why I went with the patch idea since that EDAC/ECC error was repeating at the end and I wasn't aware of that firmware reset you recently had.

For a shot in the dark -- Based on a Gigabyte thread from a two years ago, that override line entry and and reverting a specific commit were needed to get around that error...I took the commit they suggested reverting and updated it for 5.3.

[EDAC_amd64_Don't_force-enable_ECC_checking_on_newer systems.myrevert.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3773145/EDAC_amd64_Don.t_force-enable_ECC_checking_on_newer.systems.myrevert.txt)

You're right, this is a weird one.

**Comment by xk0niR** [comment] 2019-10-25 19:10
Sorry, but it still won´t boot.
I checked the ECC setting and it was set to auto (auto = enabled). Disabling ECC and building the kernel with your new patch didn´t help.

Here is a new dmesg after booting with nomodeset. I can just see it complaining now about ECC being disabled but I am bad at reading logs.

[bootFailure.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3773425/bootFailure.log)

I guess in the end it may be better not to invest too much time into it if the 5.4 tkg works for me. But still this is weird and it would be nice to know the problem.

Oh, I am often a person who attracts problems.

**Comment by fluffykittyrevenge** [comment] 2019-10-25 20:03
Me too.  That's why I don't mind helping since it may possibly help with problems I bring upon myself in the future.

Saw another error in your log:
```
[   17.742457] ccp 0000:0d:00.1: sev command 0x4 timed out, disabling PSP 
[   17.742460] ccp 0000:0d:00.1: SEV: failed to get status. Error: 0x0
```
and, going on this [Arch thread](https://bbs.archlinux.org/viewtopic.php?id=249808), setting `CONFIG_CRYPTO_DEV_SP_PSP=n` may work for that. 

IMHO, it's easiest to test by directly editing config.x86_64 and passing `--skipinteg` to makepkg...since I have no experience with the config fragments used here :blush:

**Comment by xk0niR** [comment] 2019-10-25 21:31
I did this and it still won´t boot. The message is gone though. I´ve also removed quiet from the bootline and I didn´t see any error while booting with nomodeset. 

Thanks for your suggestion, I´ve disabled ECC.
Here is my latest dmesg. As said this error is gone.

[bootFail.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3773864/bootFail.log)

The last problem I see inside the log is:
[    5.561453] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    5.563427] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    5.563449] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    5.563450] cfg80211: failed to load regulatory.db
(line 1011ff.)

I am not sure what this is about but from Google it seems it may could cause an udev lockup. I might try compiling with CONFIG_CFG80211=n but I feel like it won´t help much too because on my current kernel it is set to =y like tkg (zcat /proc/config.gz | grep CONFIG_CFG80211)

**Comment by fluffykittyrevenge** [comment] 2019-10-25 22:55
Did a bit of searching and according to an LKML page, that ECC log spam is normal on motherboards that support both types of memory but aren't using ECC ram.

Just going over your logfile:

```
[    0.762213] zswap: default compressor lz4 not available
[    0.762214] zswap: pool creation failed
```
is fixed by adding `lz4 lz4_compress` to MODULES=().  I had that one before.  You'll also want to add `zswap.zpool=z3fold` to your kernel command line to take full advantage of lz4.

```
[   13.229950] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[   13.229951] cfg80211: failed to load regulatory.db
```

can be caused by an outdated or on CRDA package.

```
[    2.337693] ahci 0000:07:00.0: failed stop FIS RX (-16)
[    2.337707] ahci 0000:07:00.0: AHCI 0001.0301 32 slots 1 ports 6 Gbps 0x1 impl SATA mode
[    2.337709] ahci 0000:07:00.0: flags: 64bit ncq sntf ilck pm led clo only pmp fbs pio slum part 
[    2.337909] scsi host0: ahci
[    2.337964] ata1: SATA max UDMA/133 abar m2048@0xfc500000 port 0xfc500100 irq 106
[    2.648965] ata1: SATA link down (SStatus 0 SControl 300)
```
Is similar to what is found in this thread that recommends adding `amd_iommu=off` to the kernel command line.  Since that's a hard drive, might be relevant.

```
[   12.759095] snd_hda_intel: probe of 0000:0b:00.1 failed with error -2
```
Not really sure on that one.

Here's a copy of the amdgpu stuff I've added to the kernel command line since they may be useful.
```
amdgpu.dpm=1 amdgpu.dc=1 amdgpu.ppfeaturemask=0xfffd7fff amdgpu.deep_color=1 amdgpu.exp_hw_support=1
```

I was about to post, saw you're updated post, and wanted to say that every single one of these errors, aside from the lz4 one (which is using zbud and not z3fold), is present in both the failing logs and xan.log.

Where it's failing on the 5.3 tkg builds is where dhcp is coming up on the xanmod build, but I don't think that's the problem.  Just a coincidence.

Looking over the xanmod patches, they include some [navi10 fixes that are present in 5.4](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=839e0f04b50441d1f6593070b574b7933e903c7c).  Making a patch from that pull request might do the trick to fix your issues.

**Comment by Tk-Glitch** [comment] 2019-10-25 23:02
`drm/i915: Favor last VBT child device with conflicting AUX ch/DDC pin` is part of -tkg so you'd want to remove that one. Everything else should be fine, and is likely to be available in 5.3.8, too. You issue definitely seems to be related to that GPU. The log is pretty ok otherwise with nomodeset.

**Comment by xk0niR** [comment] 2019-10-26 10:05
I still can´t boot.
@ fluffykittyrevenge: Thanks a lot for your suggestions I´ll try them later.

@Tk-Glitch: I downloaded this patch: https://patchwork.freedesktop.org/patch/335582/
Renamed it to .myrevert and build again without success. I also tried modifying kernel bootline by adding "modprobe.blacklist="i915"" without any different result.

Here is the dmesg:
[i915Revert.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3774702/i915Revert.log)

(Note: It contains the other errors discussed before because I just tried this patch).

I might try all of fluffykittyrevenge suggestions + the patch + using nconfig to disable i915 module...
So much compiling the last days...

As you said I might better wait for 5.3.8 if it is such a big weird mess.

**Comment by fluffykittyrevenge** [comment] 2019-10-26 15:14
@xk0niR That i915 doesn't effect your situation.  What you have to do is go through the [amd-staging-drm-next](https://cgit.freedesktop.org/~agd5f/linux/log/?h=amd-staging-drm-next) commit history and cherry-pick in the individual commits that relate to Navi, AMDGPU, PowerPlay.

What @Tk-Glitch was saying was that one of the i915 patches in the link to the pull request is already part of the kernel so you wouldn't need it.  What you need are the AMDGPU commits from that link at a minimum as well as the AMDGPU commits from a previous drm-next pull request.

Anyhoo, I'm in the middle of a straight pull of amd-staging-drm-next into 5.3.7 and making a patch out of that.  Give me some time to finish and test that and with any luck it'll solve your problem (AFAICT, it contains every single community patch for AMDGPUs + all the Navi (and more) fixes going into 5.4).

**Comment by fluffykittyrevenge** [comment] 2019-10-26 16:05
Following the (paraphrased) words of Linus -- if it compiles, it's good -- here's the patch.  Building my ZFS module now.  I forgot to pull last night's commits before building, but I doubt that'll matter with what we're testing.  The only community patch I used was the zstd patch.  Every patch regarding AMDGPU is here (as well as what's in the 5.5 drm pull article on Phoronix this morning :smile_cat: ).

About to reboot and actually test this.  Just have to finish setting up multiple kernels in GRUB before I reboot since 5.3 TKG is currently my only kernel installed and I don't feel comfortable having just an experimentally patched kernel for testing on my system.

[5.4drm.mypatch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3774998/5.4drm.mypatch.txt)

@Tk-Glitch Have you considered a linux-git-tkg package?  Based off the [stable kernel repo](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/) and not Linus's repo.  Just thinking that all the kernels could become one package and all we'd have to change is the kernel version in a config file.  The patch scripting would be "very fun" so I can understand why you haven't.

**Comment by xk0niR** [comment] 2019-10-27 09:45
@fluffykittyrevenge Your patch is working great! I´ve compiled without any error and boot works fine now (I already was on the git version of your mentioned packages because I followed https://wiki.archlinux.org/index.php/Navi_10 already).

Thanks so much for your efforts and help.
Issue is fixed so it may can be closed.

**Comment by Tk-Glitch** [comment] 2019-10-27 09:58
Can't help but thank @fluffykittyrevenge as well :)
Well, the issue is "fixed" yes and no. Current stable kernel's Navi support is plain terrible as we noticed. Hopefully 5.3.8 will release with actual backports. It's been 4 months since release and these GPUs are only barely usable with a collection of cherry picked patches for kernel and mesa. This is really concerning and sad.

**Comment by fluffykittyrevenge** [comment] 2019-10-27 12:04
Aside from saying "switch to an AMD staging kernel"* which is technically the correct solution for this issue, crossing my fingers and pulling against one for a patch was the next best thing to try (especially once I started seeing just how many commits were Navi related and having no idea what was necessary or not).

That patch essentially brings the AMDGPU stack up to what is currently planned to go into Linux 5.5 as well as contains some Intel fixes so i915 users may benefit from the patch too.  

@xk0niR -- I have no idea how long the patch will work with 5.3 kernels or if it will even work with 5.3.8.  If it quits working and is still needed, let me know and I'll try to get around to updating it.  Since I have everything on hand, it's literally:

- git fetch --all
- git switch linux-5.3.y
- git reset --hard last_5.3.y_commit
- git switch -c new_branch
- git fetch some_AMD_commit
- git mergetooll
- git diff linux-5.3.y..new_branch

*Those AMD kernels are 90% why I asked that question about a linux-git-based PKGBUILD.  The 10% would be to combine all the kernels into one package with a _kernel_branch=5.3.y option.  That's actually something I want to do and might get around to it when I finish my rewrite of.....well, I'll leave y'all in suspense and say that'll hopefully be a pull request tomorrow and is not kernel related :cat2:

**Comment by xk0niR** [comment] 2019-10-29 11:38
@fluffykittyrevenge: Your patch isn´t working anymore sadly on 5.3.8 but still needed (doesn´t boot without it)
patching file include/uapi/linux/media-bus-format.h
patching file security/device_cgroup.c
==> FEHLER: Ein Fehler geschah in prepare().
    Breche ab...
  -> exit cleanup done
I tried following your steps but I am not sure.
 * git clone git://people.freedesktop.org/~agd5f/linux Is this correct?

**Comment by fluffykittyrevenge** [comment] 2019-11-01 12:14
Here you go.  Haven't been on GitHub since the other day so I only saw this an hour ago.  Haven't tested this either.

[amd-staging.mypatch.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3797800/amd-staging.mypatch.txt)

Yep, that's the AMDGPU goldmine.  Making the patch is a lot easier on my end because I have the commit history so all I have to do is ensure linux-5.3-y is clean, pull it with its master to get the .8 changes, switch -c to a new branch, pull my previous patch branch, fix any issues, pull from agd5f amd-staging-drm-next, fix any issues (none this time).

You have to swap the "pull my previous patch branch" step with "git apply patch-name" and go from there.

**Comment by Tk-Glitch** [comment] 2019-11-29 01:19
Now that 5.4 got released I think we can close this.

**Closed by Tk-Glitch** 2019-11-29 01:19 UTC
Labels: KERNEL, upstream
