### ISSUE TITLE
[wine-tkg-git] ERROR: A failure occurred in build when _steam_fix="true"

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#390] opened 2019-11-13 16:34 UTC
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3842332/last_build_config.log)
![Screenshot from 2019-11-13 21-32-02](https://user-images.githubusercontent.com/36989404/68783768-51a95b00-065d-11ea-8ab2-5794f2eb95f3.png)

**Comment by ErdeFB** [comment] 2019-11-13 16:46
Known issue and duplicate of #388 
Disable steam.patch in the meanwhile before it gets sorted if you are in a hurry to compile a build.

**Comment by Kerrung** [comment] 2019-11-13 16:49
> Known issue and duplicate of #388
> Disable steam.patch in the meanwhile before it gets sorted if you are in a hurry to compile a build.

This is me who is the author of issue #388, which is already closed with the marked "fixed ', but then it turns out that it is not" fixed ".

**Comment by ErdeFB** [comment] 2019-11-13 17:06
Have a look at #389 for the authors comment about it that was posted just recently.

**Closed** 2019-11-13 19:48 UTC
