### ISSUE TITLE
configure: error: FreeType 64-bit development files not found. Fonts will not be built.

### ISSUE THREAD

**Issue by mda63** [Tk-Glitch/PKGBUILDS#201] opened 2019-05-18 18:46 UTC
Trying like crazy to get this built in the latest Arch with GNOME.

I've installed Freetype and have even confirmed the presence of ft2build.h, which it claims not to be able to find.

I'm stuck, please help an annoying newbie!

**Comment by mda63** [comment] 2019-05-18 18:47
Ah god, sorry -- this is for wine-tkg-git

**Comment by Tk-Glitch** [comment] 2019-05-19 06:19
Please provide your `config.log` file found in `*/wine-tkg-git/src/wine-tkg-*-git-64-build/`
Thanks!

**Comment by Tk-Glitch** [comment] 2019-05-25 13:51
No feedback nor logs provided. I'm closing for now. I'll reopen if needed.

**Comment by soredake** [comment] 2019-11-06 12:27
@Tk-Glitch hi, i reinstalled packages (bad idea?) and now configure can't find freetype.
[config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3814376/config.log)

**Comment by Tk-Glitch** [comment] 2019-11-06 12:33
The `freetype2` package definitely provides the `ft2build.h` file configure doesn't find, and I also can't reproduce your issue on Arch.

**Comment by soredake** [comment] 2019-11-06 12:34
File is here
```
ls -l /usr/include/freetype2/ft2build.h
-rw-r--r-- 1 root root 1.1K Jul  2 14:33 /usr/include/freetype2/ft2build.h
```

**Comment by Tk-Glitch** [comment] 2019-11-06 12:35
What package have you reinstalled?

**Comment by soredake** [comment] 2019-11-06 12:37
All, not including aur packages https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Reinstalling_all_packages

**Comment by soredake** [comment] 2019-11-06 12:52
My filesystem is migrated from gentoo and year ago, maybe it's time install arch from scratch.

**Comment by Tk-Glitch** [comment] 2019-11-06 14:33
`pkgconf` is installed, right?

**Comment by soredake** [comment] 2019-11-06 15:13
Oh, it missing, seems my install reason for base-devel group packages are changed to "deps" and `yay -c` deleted these packages, thanks.

**Comment by Tk-Glitch** [comment] 2019-11-06 15:39
All fixed then?

**Comment by soredake** [comment] 2019-11-06 15:54
Configure doesn't error now, so yes, thanks for help!

**Comment by Tk-Glitch** [comment] 2019-11-06 15:56
Great news :)

**Closed by Tk-Glitch** 2019-11-06 15:56 UTC
Labels: frog :frog:
