### ISSUE TITLE
[wine-tkg-git] Can't to compile with commit e350f39d1f1fe8a617618c632a635dfc756da409

### ISSUE THREAD

**Issue by Kerrung** [Tk-Glitch/PKGBUILDS#556] opened 2020-05-05 10:06 UTC
OS: Arch Linux;
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4580103/last_build_config.log)
Commit: https://github.com/Tk-Glitch/PKGBUILDS/commit/e350f39d1f1fe8a617618c632a635dfc756da409
![Screenshot from 2020-05-05 15-00-35](https://user-images.githubusercontent.com/36989404/81055310-e0e34d00-8ee1-11ea-909b-9f1c2f7e96cb.png)

**Comment by Kerrung** [comment] 2020-05-05 10:27
OS: Arch Linux;
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/4580179/last_build_config.log)
Commit: e350f39
![Screenshot from 2020-05-05 15-25-25](https://user-images.githubusercontent.com/36989404/81056879-cc548400-8ee4-11ea-88f7-7b2cf12bccf8.png)

**Comment by EdLovecraft** [comment] 2020-05-05 12:14
same here

**Comment by Tk-Glitch** [comment] 2020-05-05 14:26
Duplicate of https://github.com/Frogging-Family/wine-tkg-git/issues/32
Please check before opening a new issue.

Also both screenshots are not the same issue, and the first one is completely useless as it doesn't show the actual error.
Please post actual logs next time, thanks.

**Closed** 2020-05-05 14:26 UTC
