### ISSUE TITLE
Unable to install dotnet40

### ISSUE THREAD

**Issue by jporterf** [Tk-Glitch/PKGBUILDS#332] opened 2019-09-30 05:47 UTC
With wine-tkg installed, I cannot get dotnet40 to install, either by winetricks or manually.  If I revert to standard wine-staging, it works.  I get the error message:
`cabinet_copy_file failed to create L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\Microsoft.VisualBasic.Activities.Compiler.dll" (error 3)`

**Comment by Tk-Glitch** [comment] 2019-09-30 09:45
I can't reproduce your issue on my end (staging 4.17.r1.g0c7512f5 based build).
Please post your `last_build_config.log` or config file so I can try a repro with a similar build to yours.

**Comment by jporterf** [comment] 2019-10-05 17:48
Sorry for the delay in replying, here are the files you requested. 
[wine-tkg.txt](https://github.com/Tk-Glitch/PKGBUILDS/files/3693558/wine-tkg.txt)
[last_build_config.log](https://github.com/Tk-Glitch/PKGBUILDS/files/3693562/last_build_config.log)

**Comment by Tk-Glitch** [comment] 2019-10-07 13:20
I noticed that you're using the MTGA crashfix, and that is known to break (among other things) dotnet40 installer. I'll add a note about it in the cfg.

**Comment by jporterf** [comment] 2019-10-07 19:04
Which is ironic, considering you need it to run the application.  I just reverted to my distro's staging to install it and back to tkg to run the application.

**Comment by Tk-Glitch** [comment] 2019-10-10 15:31
That's is indeed ironic, and that's also part of why that hack isn't suitable for staging :P
I guess I can close this.

**Closed by Tk-Glitch** 2019-10-10 15:31 UTC
