### ISSUE TITLE
When updating proton-tkg / deleting older versions, Steam will randomly get confused, and think that a game is 100% corrupted, requiring a full redownload

### ISSUE THREAD

**Issue by Valmar33** [Tk-Glitch/PKGBUILDS#246] opened 2019-07-12 13:08 UTC
https://github.com/ValveSoftware/steam-for-linux/issues/6383

The replier, @dreamer, thinks that it might be due to proton-tkg quite possibly including version information in the internal name, which is causing Steam to act weird.

**Comment by BangL** [comment] 2019-07-12 13:17
first..
what do you mean by "deleting older versions"?
removing the folder manually, or using the uninstaller script by tkg?

second..
did you maybe set a custom proton version globally (in settings > steam play > enable steam play for all other titles)?
in case you did: thats probably where the problem comes from. i had similar issues, when i did.
make sure to keep valve's proton 4.2 as global version, and then only set custom versions per game.

**Comment by Valmar33** [comment] 2019-07-12 13:20
First ~ I use TkG's uninstaller.

Second ~ ah... yes, I did try and set `proton-tkg` as the global version. :/

Steam still shouldn't bork out...

**Comment by BangL** [comment] 2019-07-12 13:24
Ok.. so that's it.
Yeah, thats actually a steam issue, it does not seem to accept custom version as global for now :/
anytime you try, it will just remove the the "enable steam play for all other titles" entirely on restart, and then steam tries to download native linux versions again.

**Comment by dreamer** [comment] 2019-07-12 14:39
@BangL You are not entirely correct. I can select my tool ([steam-dos](https://github.com/dreamer/steam-dos)) as default compatibility tool for for Steam and it will *not* trigger re-download of all games. I would not recommend it to users anyway, because my tool is designed for DOS games only.

This problem is caused (or at least made worse) by compatibility tool changing it's internal name during update. Steam remembers internally which tool name is used for which game, but when tool updates it's *.vdf file and changes the name, Steam gets confused, loses track of which depot is used to update the game and sometimes re-downloads all files.

To work around this, I stopped including versions in internal name of my tool.

I *think* official Proton has some workarounds in Steam client to handle updates that change Proton's internal name, but it does not work for community developed tools (or maybe it would work if Steam allowed distribution in-client).

**Comment by Tk-Glitch** [comment] 2019-07-12 21:26
The problem doesn't exist as long as you :
- are using the uninstaller (if steam is open and not detected by the uninstaller you'll face the issue, but that shouldn't happen anymore).
- don't have a game running while updating the same version of proton (for example building 4.12r1 while you already have a 4.12r1 build installed). That case is not handled by the script.
- don't try to set a proton-tkg version globally. It might look like it works at first, but it's acting weird.

There is, however, another bug that's unrelated to proton-tkg with the shader caches handling. Some games (I have faced the issue with Bayonetta and Quake Champions myself) will randomly fail to validate something and enter an update loop that will never end. I have disabled shader precaching for that reason and never faced such an issue again. It's probably not viable for AMD GPU users though, but that's not something I can fix on my end.

**Comment by Faalagorn** [comment] 2019-07-12 22:10
I didn't encounter that problem having proton-tkg globally and having shaders (on AMD if that matters), but maybe it's just a matter of time? :frog:

**Comment by Tk-Glitch** [comment] 2019-07-12 22:16
To be honest it shouldn't happen anymore with the steam running check. The bug regarding globally set custom proton shouldn't trigger a checking failure. This whole issue might have nothing to do with custom proton to begin with.

**Comment by skeevy420** [comment] 2019-07-24 13:34
> I have disabled shader precaching for that reason and never faced such an issue again. It's probably not viable for AMD GPU users though, but that's not something I can fix on my end.

I ended up doing that with for my RX 580 last month for a completely unrelated reason.  Every time I'd fire up Steam it would want to download many GBs worth of shader cache and I have a crappy cable company that has bandwidth quotas...I'll leave it at that because I can only use very colorful words to describe them...  

As far as I could tell, it wanted to download so much shader cache because I was and am using Steam Beta.

Because it can cost money due to wasting a lot of bandwidth, I consider disabling shader precaching a perfectly viable option for AMD GPU users.

**Comment by Tk-Glitch** [comment] 2019-07-24 13:37
Quake Champions and Path of Exile are both downloading multiple GBs of shader caches with the option enabled so yeah.. Not really low bandwidth/quota friendly for sure.

**Comment by Tk-Glitch** [comment] 2019-09-07 17:15
Was https://github.com/Tk-Glitch/PKGBUILDS/commit/2b68e3773b9c9f194222d8dd78a850102c33a7a4 enough of a workaround for this to not happen again? I definitely didn't encounter such a thing again myself since.

**Comment by Tk-Glitch** [comment] 2019-12-06 07:38
Seems to be kinda silent in here so I guess my workaround works for the most part. I have encountered the issue once with no custom proton installed at all, so this is definitely an issue with the steam client and not directly linked to custom compatibility tools.

I've been unable to reproduce the issue since, sadly, so it's a bit annoying. But the "issue on my side" is fixed by enforcing the client to be closed before installing proton-tkg. If you're not building proton-tkg yourself and are using prebuilts, make sure to close the steam client before copying files.

Let's close this. Will reopen if needed.

**Closed by Tk-Glitch** 2019-12-06 07:38 UTC
Labels: upstream
