### ISSUE TITLE
"fixme" something

### ISSUE THREAD

**Issue by Danilopereira82** [Tk-Glitch/PKGBUILDS#365] opened 2019-11-02 21:08 UTC
004d:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
004d:fixme:exec:SHELL_execute flags ignored: 0x00000100
004f:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub

this is all i get

other programs work

but when i try to run Dark Souls this happens
some days ago the game was working

but i instaled the same way today and it doesn't work

**Comment by Tk-Glitch** [comment] 2019-11-06 09:47
That "log" is clearly truncated. We'll need more details to help you here.

**Comment by Tk-Glitch** [comment] 2019-11-07 16:14
You might want to give the `_kernelbase_reverts="true"` option a try

**Comment by Danilopereira82** [comment] 2019-11-10 00:06
> That "log" is clearly truncated. We'll need more details to help you here.
well the problem was gone after some updates
but i get this now

0009:err:module:LdrInitializeThunk "steam_api.dll" failed to initialize, aborting
0009:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files\\BANDAI NAMCO Games\\DARK SOULS - Prepare To Die Edition\\DATA\\DARKSOULS.exe" failed, status c0000142

**Comment by Tk-Glitch** [comment] 2019-11-10 10:12
I didn't think you were using the first version of the game (I do not have the remaster), so I installed it to try to get a reproduction, but the game works just fine on my end.

Can you please provide your `last_build_config.log`?

**Comment by Danilopereira82** [comment] 2019-11-10 18:43
> last_build_config.log

i don't compile by myself, i download from chaotic-aur repository

**Comment by Danilopereira82** [comment] 2019-11-12 16:22
i get all this

000b:fixme:winediag:start_process Wine TkG 4.19 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
001b:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a068): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de8-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a088): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de9-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0a8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dea-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0c8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7deb-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0e8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dec-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a108): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7ded-0a80-11d8-ad15-505054503030}
001e:fixme:win:RegisterDeviceNotificationW (hwnd=0x115a50, filter=0x64fe1c,flags=0x00000001) returns a fake device notification handle!
002a:fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x32e700, (null), (null), 0x6cd20188): stub
002a:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
002a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
002a:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0030:fixme:ole:CoInitializeSecurity (001F8E70,-1,00000000,00000000,4,2,00000000,0,00000000) - stub!
0030:fixme:ole:CoResumeClassObjects stub
0038:fixme:crypt:Collection_release Unimplemented flags 1
0038:fixme:crypt:ProvStore_release Unimplemented flags 1
0038:fixme:crypt:CRYPT_RegCloseStore Unimplemented flags: 00000001
0038:fixme:crypt:MemStore_release Unimplemented flags 1
0038:fixme:advapi:ParseStringSidToSid String constant not supported: L".D"
0038:fixme:iphlpapi:NotifyAddrChange (Handle 0xfafba8, overlapped 0x1162f88): stub
0038:fixme:wtsapi:WTSEnumerateSessionsW Stub 00000000 0x00000000 0x00000001 00FAFBB0 00FAFBA8
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
0040:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0040:fixme:ole:NdrCorrelationInitialize (001F05E8, 001F01E8, 1024, 0x0): semi-stub
0038:fixme:ole:NdrCorrelationInitialize (00FAF834, 00FAF910, 1024, 0x0): semi-stub
0038:fixme:ole:NdrCorrelationFree (00FAF834): stub
0040:fixme:ole:NdrCorrelationFree (001F05E8): stub
0043:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub

**Comment by telans** [comment] 2019-11-13 03:09
`002a:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.`

Do you have all of `smbclient cifs-utils libwbclient lib32-libldap samba` installed?

**Comment by Danilopereira82** [comment] 2019-11-13 10:22
looks like i was missing samba
i installed but still got this

000b:fixme:winediag:start_process Wine TkG 4.19 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a060, {485e7de8-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a068): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de8-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a080, {485e7de9-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a088): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7de9-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0a0, {485e7dea-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0a8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dea-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0c0, {485e7deb-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0c8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7deb-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a0e0, {485e7dec-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a0e8): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7dec-0a80-11d8-ad15-505054503030}
001b:fixme:ntdll:EtwRegisterTraceGuidsW (0x100778a, 0x100a100, {485e7ded-0a80-11d8-ad15-505054503030}, 1, 0x32fe90, (null), (null), 0x100a108): stub
001b:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {485e7ded-0a80-11d8-ad15-505054503030}
001e:fixme:win:RegisterDeviceNotificationW (hwnd=0x115b88, filter=0x64fe1c,flags=0x00000001) returns a fake device notification handle!
002a:fixme:ntdll:EtwRegisterTraceGuidsW (0x6cd15f38, 0x6cd20180, {e2821408-c59d-418f-ad3f-aa4e792aeb79}, 1, 0x32e700, (null), (null), 0x6cd20188): stub
002a:fixme:ntdll:EtwRegisterTraceGuidsW   register trace class {e2821408-c59d-418f-ad3f-aa4e792aeb79}
002a:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0030:fixme:ole:CoInitializeSecurity (001F8FF0,-1,00000000,00000000,4,2,00000000,0,00000000) - stub!
0030:fixme:ole:CoResumeClassObjects stub
0037:fixme:crypt:Collection_release Unimplemented flags 1
0037:fixme:crypt:ProvStore_release Unimplemented flags 1
0037:fixme:crypt:CRYPT_RegCloseStore Unimplemented flags: 00000001
0037:fixme:crypt:MemStore_release Unimplemented flags 1
0037:fixme:advapi:ParseStringSidToSid String constant not supported: L".D"
0037:fixme:iphlpapi:NotifyAddrChange (Handle 0xe9fba8, overlapped 0x1162f88): stub
0037:fixme:wtsapi:WTSEnumerateSessionsW Stub 00000000 0x00000000 0x00000001 00E9FBB0 00E9FBA8
0009:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0009:fixme:exec:SHELL_execute flags ignored: 0x00000100
danilop@danilo ~/w/d/P/N/DarkSouls> 0040:fixme:heap:RtlSetHeapInformation 0x110000 1 (nil) 0 stub
0040:fixme:ole:NdrCorrelationInitialize (001F05E8, 001F01E8, 1024, 0x0): semi-stub
0037:fixme:ole:NdrCorrelationInitialize (00E9F834, 00E9F910, 1024, 0x0): semi-stub
0037:fixme:ole:NdrCorrelationFree (00E9F834): stub
0040:fixme:ole:NdrCorrelationFree (001F05E8): stub
0043:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub

**Comment by Tk-Glitch** [comment] 2019-12-15 09:34
Since the issue seems to be related to some cracked executable I'll close this

**Closed by Tk-Glitch** 2019-12-15 09:34 UTC
Labels: question
